def return_abbr(name):

    teams = {
    "Tuckahoe": "T",
    "Overlee": "O",
    "Chesterbrook": "CB",
    "Donaldson Run": "DR",
    "Highlands Swim": "HS",
    "McLean": "ML",
    "Old Keene Mill": "OKM",
    "Crosspointe": "CP",
    "Langley": "L",
    "Kent Gardens": "KG",
    "Little Rocky Run": "LRR",
    "Fair Oaks": "FO",
    "Hunt Valley": "HV",
    "High Point Pool": "HPP",
    "Hamlet": "HSC",
    "Wakefield Chapel": "WC",
    "Orange Hunt": "OH",
    "Cardinal Hill": "CH",
    "Oakton": "OAK",
    "Mantua": "M",
    "Vienna Woods": "VW",
    "Hiddenbrook": "HB",
    "Little Hunting Park": "LHP",
    "Lee Graham": "LG",
    "Vienna Aquatic": "VAC",
    "Virginia Hills": "VH",
    "Sleepy Hollow Rec": "SHR",
    "Virginia Run": "VR",
    "Dowden Terrace": "DT",
    "Mount Vernon Park": "MVP",
    "Pinecrest": "PC",
    "South Run": "SOR",
    "Dunn Loring": "DL",
    "Fairfax Station": "FS",
    "Hunter Mill": "HTM",
    "Lakevale Estates": "LE",
    "Springboard": "SB",
    "Poplar Heights": "PH",
    "Fairfax": "F",
    "Cottontail": "CT",
    "Ravensworth Farm": "R",
    "Brandywine": "B",
    "Dominion Hills": "DH",
    "Sleepy Hollow B & R": "SHB",
    "Seals": "SHB",
    "Canterbury Woods": "CW",
    "C-Serpents": "CW",
    "Rolling Hills": "RH",
    "Lakeview": "LV",
    "Country Club Hills": "CCH",
    "Parklawn": "PL",
    "Sully Station": "SS",
    "Villa Aquatic": "VA",
    "Arlington Forest": "AF",
    "Camelot": "CCC",
    "Walden Glen": "WG",
    "Waynewood": "WW",
    "Fox Hunt": "FX",
    "Mansion House": "MHC",
    "Holmes Run Acres": "HRA",
    "Truro": "THA",
    "Great Falls": "GF",
    "Hollin Meadows": "HM",
    "Highland Park": "HP",
    "Mosby Woods": "MW",
    "Greenbriar": "G",
    "Sideburn Run": "SR",
    "Fox Mill Woods": "FMW",
    "Forest Hollow": "FH",
    "Kings Ridge": "KR",
    "Daventry": "DV",
    "Poplar Tree": "PT",
    "Rolling Forest": "RF",
    "Stratford": "SRA",
    "Brookfield": "BF",
    "Fairfax Club Estates": "FCE",
    "Woodley": "W",
    "Riverside Gardens": "RG",
    "Laurel Hill": "LH",
    "Sully Station II": "SS2",
    "Shouse Village": "SV",
    "Rolling Valley": "RV",
    "Hayfield Farm": "HF",
    "Parliament": "PAR",
    "Somerset-Olde Creek": "SOC",
    "Fox Mill Estates": "FME",
    "Lincolnia Park": "LP",
    "Commonwealth": "CSC",
    "Burke Station": "BKS",
    "Lake Braddock": "LB",
    "Annandale": "A",
    "Rutherford": "RFD",
    "Hollin Hills": "HH",
    "Long Branch": "LBR",
    "Herndon": "H",
    "Village West": "V",
    "Ilda Community": "IC",
    "Broyhill Crest": "BC",
    "Pleasant Valley": "PV",
    "Newington Forest": "NF",
    "North Springfield": "NS",
    "Springfield": "S",
    "Pinewood Lake": "PW",
    "Edsall Park": "EP",
    }


    return teams[name]