/*
-- Query: SELECT * FROM team
LIMIT 0, 1000

-- Date: 2024-12-01 14:44
*/
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('A','Annandale','7530 Little River Turnpike Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('AF','Arlington Forest','5401 North Carlin Springs Road Arlington, VA 22203');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('B','Brandywine','9537 Helenwood Dr Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('BC','Broyhill Crest','7212 Early Street Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('BF','Brookfield','13615 Pennsboro Drive Chantilly, VA 20151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('BKS','Burke Station','5820 Ridge Ford Drive Burke, VA 22015');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CB','Chesterbrook','1812 Kirby Road Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CCC','Camelot','3604 Balin Court Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CCH','Country Club Hills','3622 Old Post Rd Fairfax, VA 22030');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CH','Cardinal Hill','9117 Westerholme Way Vienna, VA 22182');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CP','Crosspointe','8275 Glen Eagle Drive Fairfax Station, VA 22039');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CSC','Commonwealth','9800 Commonwealth Blvd Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CT','Cottontail','7000 Cottontail Court Springfield, VA 22153');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('CW','Canterbury Woods','5101 Southampton Dr Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('DH','Dominion Hills','6000 Wilson Boulevard Arlington, VA 22205');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('DL','Dunn Loring','8326 Cottage Street Vienna, VA 22180');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('DR','Donaldson Run','2729 Marcey Road Arlington, VA 22207');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('DT','Dowden Terrace','Address not found on the team\'s page.');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('DV','Daventry','7721 Painted Daisy Drive Springfield, va 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('EP','Edsall Park','5505 Montgomery St.Springfield, VA 22151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('F','Fairfax','4200 Roberts Road Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FCE','Fairfax Club Estates','5601 Snowy Owl Dr.Fairfax, Va 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FH','Forest Hollow','4330 Old Columbia Pike Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FME','Fox Mill Estates','2720 Viking Drive Herndon, VA 20171');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FMW','Fox Mill Woods','2634 A Black Fir Court Reston, VA 20191');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FO','Fair Oaks','3720 Charles Stewart Drive Fairfax, VA 22033');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FS','Fairfax Station','6203 Old Arrington Dr.Fairfax Station, VA 22039');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('FX','Fox Hunt','7024 Spaniel Rd Springfield, VA 22153');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('G','Greenbriar','13001 Point Pleasant Drive Fairfax, VA 22033');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('GF','Great Falls','761 Walker Road Great Falls, VA 22066');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('H','Herndon','1114 Monroe St.Herndon, VA 20170');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HB','Hiddenbrook','1508 A Sadlers Wells Dr Herndon, VA 20170');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HF','Hayfield Farm','7820 Hayfield Road Alexandria, VA 22315');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HH','Hollin Hills','1602 Paul Spring Road Alexandria, VA 22307');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HM','Hollin Meadows','2500 Woodlawn Trail Alexandria, VA 22306');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HP','Highland Park','6406 Telegraph Road Alexandria, VA 22310');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HPP','High Point Pool','6840 Woodland Drive Falls Church, VA 22046');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HRA','Holmes Run Acres','3451 Gallows Road Falls Church, VA 22042');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HS','Highlands Swim','1515 Bryan Branch Rd.Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HSC','Hamlet','8209 Dunsinane Court Mc Lean, VA 22102');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HTM','Hunter Mill','10339 Brittenford Drive Vienna, VA 22182');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('HV','Hunt Valley','7100 Sydenstricker Road Springfield, VA 22153');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('IC','Ilda Community','Address not found on the team\'s page.');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('KG','Kent Gardens','1906 Westmoreland Road Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('KR','Kings Ridge','4850 Gainsborough Drive Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('L','Langley','728 Live Oak Dr.Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LB','Lake Braddock','9528 Ashbourn Dr.Burke, VA 22015');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LBR','Long Branch','9100 Burnetta Drive Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LE','Lakevale Estates','2554 Oak Valley Drive Vienna, VA 22180');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LG','Lee Graham','7319 Lee Highway Falls Church, VA 22042');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LH','Laurel Hill','8380 Laurel Crest Drive Lorton, VA 22079');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LHP','Little Hunting Park','7000 Canterbury Lane Alexandria, VA 22307');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LP','Lincolnia Park','6501 Montrose St Alexandria, VA 22312');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LRR','Little Rocky Run','6201 Sandstone Way Clifton, VA 20124');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('LV','Lakeview','5352 Gainsborough Dr Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('M','Mantua','9330 Pentland Place Fairfax, VA 22031');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('MHC','Mansion House','9321 Old Mount Vernon Rd Alexandria, VA 22309');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('ML','McLean','1700 Margie Drive Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('MVP','Mount Vernon Park','8042 Fairfax Road Alexandria, VA 22308');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('MW','Mosby Woods','3136 Fair Woods Parkway (previously Plantation)Fairfax, VA 22030');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('NF','Newington Forest','8201 Southrun Road Springfield, VA 22153');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('NS','North Springfield','Address not found on the team\'s page.');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('O','Overlee','6030 Lee Highway Arlington, VA 22205');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('OAK','Oakton','11714 Flemish Mill Court Oakton, VA 22124');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('OH','Orange Hunt','8600 Bridlewood Drive Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('OKM','Old Keene Mill','9534 Orion Ct.Burke, VA 22015');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PAR','Parliament','8510 Parliament Drive Springfield, VA 22151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PC','Pinecrest','12515 Pinecrest Road Herndon, VA 20171');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PH','Poplar Heights','2463 Buckelew Falls Church, VA');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PL','Parklawn','6011 Crater Place Alexandria, va 22312');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PT','Poplar Tree','13516 Point Pleasant Drive Chantilly, VA 20151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PV','Pleasant Valley','4347 Cub Run Road Chantilly, VA 20151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('PW','Pinewood Lake','8159 Fernlake Ct.Alexandria, VA 22309');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('R','Ravensworth Farm','5210 Inverchapel Road Springfield, VA 22151');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('RF','Rolling Forest','7011 Flax Street Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('RFD','Rutherford','4609 Marley Rd.Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('RG','Riverside Gardens','8633 Buckboard Drive Alexandria, VA 22308');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('RH','Rolling Hills','8301 Carrleigh Parkway Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('RV','Rolling Valley','7019 Ashbury Dr Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('S','Springfield','7400 Highland Street Springfield, VA 22150');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SB','Springboard','Address not found on the team\'s page.');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SHB','Sleepy Hollow B & R','3516 Sleepy Hollow Road Falls Church, VA 22044');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SHR','Sleepy Hollow Rec','3538 Sleepy Hollow Road Falls Church, VA 22042');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SOC','Somerset-Olde Creek','9705 Laurel Street Fairfax, VA 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SOR','South Run','9908 South Park Circle Fairfax Station, VA 22039');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SR','Sideburn Run','10603 Zion Drive Fairfax, Va 22032');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SRA','Stratford','2300 Brintizer way Alexandria, VA 22308');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SS','Sully Station','5101 Sequoia Farms Drive Centreville, VA 20120');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SS2','Sully Station II','5501 Sully Park Drive Centreville, VA 20120');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('SV','Shouse Village','1432 Towlston Road Vienna, VA 22182');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('T','Tuckahoe','1814 Great Falls Street Mc Lean, VA 22101');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('THA','Truro','4146 Elizabeth Lane Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('V','Village West','7008 Elkton Drive Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('VA','Villa Aquatic','4299 Andes Drive Fairfax, VA 22030');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('VAC','Vienna Aquatic','625 Marshall Rd Vienna, VA 22180');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('VH','Virginia Hills','6500 Virginia Hills Pool Dr. formerly Robinson Dr.Alexandria, VA 22310');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('VR','Virginia Run','15355 Wetherburn Court Centreville, VA 20120');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('VW','Vienna Woods','109 Harmony Drive SWVienna, VA 22182');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('W','Woodley','7421 Camp Alger Avenue Falls Church, VA 22042');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('WC','Wakefield Chapel','4627 Holborn Ave.Annandale, VA 22003');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('WG','Walden Glen','6126 Harmon Place Springfield, VA 22152');
INSERT INTO `` (`teamID`,`teamName`,`location`) VALUES ('WW','Waynewood','1027 Dalebrook Drive Alexandria, VA 22308');
