INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 25M 8&U', 1, 'Boys', '8&U', 25, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50M 9-10', 3, 'Boys', '9-10', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50M 11-12', 5, 'Boys', '11-12', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50M 13-14', 7, 'Boys', '13-14', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50M 15-18', 9, 'Boys', '15-18', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 25M 8&U', 11, 'Boys', '8&U', 25, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50M 9-10', 13, 'Boys', '9-10', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50M 11-12', 15, 'Boys', '11-12', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50M 13-14', 17, 'Boys', '13-14', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50M 15-18', 19, 'Boys', '15-18', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 25M 8&U', 21, 'Boys', '8&U', 25, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50M 9-10', 23, 'Boys', '9-10', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50M 11-12', 25, 'Boys', '11-12', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50M 13-14', 27, 'Boys', '13-14', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50M 15-18', 29, 'Boys', '15-18', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 25M 8&U', 31, 'Boys', '8&U', 25, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 25M 9-10', 33, 'Boys', '9-10', 25, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50M 11-12', 35, 'Boys', '11-12', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50M 13-14', 37, 'Boys', '13-14', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50M 15-18', 39, 'Boys', '15-18', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 100M Relay 8&U', 41, 'Boys', '8&U', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 200M Relay Mixed Age', 51, 'Boys', 'Mixed Age', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 9-10', 43, 'Boys', '9-10', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 11-12', 45, 'Boys', '11-12', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 13-14', 47, 'Boys', '13-14', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 200M Relay 15-18', 49, 'Boys', '15-18', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 25M 8&U', 2, 'Girls', '8&U', 25, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50M 9-10', 4, 'Girls', '9-10', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50M 11-12', 6, 'Girls', '11-12', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50M 13-14', 8, 'Girls', '13-14', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50M 15-18', 10, 'Girls', '15-18', 50, 'Free', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 25M 8&U', 12, 'Girls', '8&U', 25, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50M 9-10', 14, 'Girls', '9-10', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50M 11-12', 16, 'Girls', '11-12', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50M 13-14', 18, 'Girls', '13-14', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50M 15-18', 20, 'Girls', '15-18', 50, 'Back', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 25M 8&U', 22, 'Girls', '8&U', 25, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50M 9-10', 24, 'Girls', '9-10', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50M 11-12', 26, 'Girls', '11-12', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50M 13-14', 28, 'Girls', '13-14', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50M 15-18', 30, 'Girls', '15-18', 50, 'Breast', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 25M 8&U', 32, 'Girls', '8&U', 25, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 25M 9-10', 34, 'Girls', '9-10', 25, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50M 11-12', 36, 'Girls', '11-12', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50M 13-14', 38, 'Girls', '13-14', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50M 15-18', 40, 'Girls', '15-18', 50, 'Fly', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 100M Relay 8&U', 42, 'Girls', '8&U', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 200M Relay Mixed Age', 52, 'Girls', 'Mixed Age', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 9-10', 44, 'Girls', '9-10', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 11-12', 46, 'Girls', '11-12', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 13-14', 48, 'Girls', '13-14', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 200M Relay 15-18', 50, 'Girls', '15-18', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 100M Relay 8&U', 14, 'Boys', '8&U', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 100M Relay 9-10', 16, 'Boys', '9-10', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 100M Relay 11-12', 18, 'Boys', '11-12', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 200M Relay 13-14', 20, 'Boys', '13-14', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 200M Relay 15-18', 22, 'Boys', '15-18', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 200M Relay Mixed Age', 2, 'Boys', 'Mixed Age', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 8&U', 4, 'Boys', '8&U', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 9-10', 6, 'Boys', '9-10', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100M Relay 11-12', 8, 'Boys', '11-12', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 200M Relay 13-14', 10, 'Boys', '13-14', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 200M Relay 15-18', 12, 'Boys', '15-18', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 100M Relay 8&U', 13, 'Girls', '8&U', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 100M Relay 9-10', 15, 'Girls', '9-10', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 100M Relay 11-12', 17, 'Girls', '11-12', 100, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 200M Relay 13-14', 19, 'Girls', '13-14', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 200M Relay 15-18', 21, 'Girls', '15-18', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 200M Relay Mixed Age', 1, 'Girls', 'Mixed Age', 200, 'Free', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 8&U', 3, 'Girls', '8&U', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 9-10', 5, 'Girls', '9-10', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100M Relay 11-12', 7, 'Girls', '11-12', 100, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 200M Relay 13-14', 9, 'Girls', '13-14', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 200M Relay 15-18', 11, 'Girls', '15-18', 200, 'Medley', 0, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys IM 100M 10&U', 41, 'Boys', '10&U', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys IM 100M 11-12', 43, 'Boys', '11-12', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys IM 100M 13-14', 45, 'Boys', '13-14', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys IM 100M 15-18', 47, 'Boys', '15-18', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls IM 100M 10&U', 42, 'Girls', '10&U', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls IM 100M 11-12', 44, 'Girls', '11-12', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls IM 100M 13-14', 46, 'Girls', '13-14', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls IM 100M 15-18', 48, 'Girls', '15-18', 100, 'IM', 1, 'M');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 25Y 8&U', 1, 'Boys', '8&U', 25, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50Y 9-10', 3, 'Boys', '9-10', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50Y 11-12', 5, 'Boys', '11-12', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50Y 13-14', 7, 'Boys', '13-14', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 50Y 15-18', 9, 'Boys', '15-18', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 25Y 8&U', 11, 'Boys', '8&U', 25, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50Y 9-10', 13, 'Boys', '9-10', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50Y 11-12', 15, 'Boys', '11-12', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50Y 13-14', 17, 'Boys', '13-14', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Back 50Y 15-18', 19, 'Boys', '15-18', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 25Y 8&U', 21, 'Boys', '8&U', 25, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50Y 9-10', 23, 'Boys', '9-10', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50Y 11-12', 25, 'Boys', '11-12', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50Y 13-14', 27, 'Boys', '13-14', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Breast 50Y 15-18', 29, 'Boys', '15-18', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 25Y 8&U', 31, 'Boys', '8&U', 25, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 25Y 9-10', 33, 'Boys', '9-10', 25, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50Y 11-12', 35, 'Boys', '11-12', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50Y 13-14', 37, 'Boys', '13-14', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Fly 50Y 15-18', 39, 'Boys', '15-18', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 100Y Relay 8&U', 41, 'Boys', '8&U', 100, 'Free', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Free 200Y Relay Mixed Age', 51, 'Boys', 'Mixed Age', 200, 'Free', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100Y Relay 9-10', 43, 'Boys', '9-10', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100Y Relay 11-12', 45, 'Boys', '11-12', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 100Y Relay 13-14', 47, 'Boys', '13-14', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Boys Medley 200Y Relay 15-18', 49, 'Boys', '15-18', 200, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 25Y 8&U', 2, 'Girls', '8&U', 25, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50Y 9-10', 4, 'Girls', '9-10', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50Y 11-12', 6, 'Girls', '11-12', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50Y 13-14', 8, 'Girls', '13-14', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 50Y 15-18', 10, 'Girls', '15-18', 50, 'Free', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 25Y 8&U', 12, 'Girls', '8&U', 25, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50Y 9-10', 14, 'Girls', '9-10', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50Y 11-12', 16, 'Girls', '11-12', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50Y 13-14', 18, 'Girls', '13-14', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Back 50Y 15-18', 20, 'Girls', '15-18', 50, 'Back', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 25Y 8&U', 22, 'Girls', '8&U', 25, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50Y 9-10', 24, 'Girls', '9-10', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50Y 11-12', 26, 'Girls', '11-12', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50Y 13-14', 28, 'Girls', '13-14', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Breast 50Y 15-18', 30, 'Girls', '15-18', 50, 'Breast', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 25Y 8&U', 32, 'Girls', '8&U', 25, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 25Y 9-10', 34, 'Girls', '9-10', 25, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50Y 11-12', 36, 'Girls', '11-12', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50Y 13-14', 38, 'Girls', '13-14', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Fly 50Y 15-18', 40, 'Girls', '15-18', 50, 'Fly', 1, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 100Y Relay 8&U', 42, 'Girls', '8&U', 100, 'Free', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Free 200Y Relay Mixed Age', 52, 'Girls', 'Mixed Age', 200, 'Free', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100Y Relay 9-10', 44, 'Girls', '9-10', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100Y Relay 11-12', 46, 'Girls', '11-12', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 100Y Relay 13-14', 48, 'Girls', '13-14', 100, 'Medley', 0, 'Y');
INSERT INTO `Event` (`eventID`, `number`, `gender`, `age_group`, `distance`, `stroke`, `individual`, `course`) VALUES ('Girls Medley 200Y Relay 15-18', 50, 'Girls', '15-18', 200, 'Medley', 0, 'Y');